var Client={};
Client.socket=io();
Client.AskNewPlayer=function(){
    Client.socket.emit('newplayer');
};
Client.socket.on('newplayer',function(data){
    AddNewPlayer(data.id,data.x,data.y);
});
Client.socket.on('allplayers',function(data){
    console.log(data);
    for(var i=0;i<data.length;i++){
        AddNewPlayer(data[i].id,data[i].x,data[i].y);
    }
});
Client.socket.on('removeplayer',function(id){
    RemovePlayer(id);
});
Client.socket.on('yourid',function(id){
    mineid=id;
    if(mineid==1)isdev=1;
});
Client.socket.on('playanims',function(id,anim){
    PlayAnims(id,anim);
});
Client.ChangeAnims=function(str){
    Client.socket.emit('changeanims',mineid,str);
};
Client.socket.on('playpic',function(id,anim){
    PlayPic(id,anim);
});
Client.ChangePic=function(str){
    Client.socket.emit('changepic',mineid,str);
};
Client.socket.on('setv',function(id,k,s){
    SetV(id,k,s);
});
Client.ChangeV=function(k,s){
    Client.socket.emit('changev',mineid,k,s);
};
Client.socket.on('setp',function(id,x,y){
    SetP(id,x,y);
});
Client.ChangeP=function(id,x,y){
    Client.socket.emit('changep',id,x,y);
};
Client.socket.on('gettd',function(k){
    istd=k;
});
Client.SendTD=function(id,k){
    Client.socket.emit('sendtd',id,k);
};